compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn.cjs
